### ISSUE TITLE
Small Key Rings Not Working

### ISSUE THREAD

**Issue by noellejfeist** [christianlegge/cojiro#2]
When collecting small key rings, they don't update the key count; it remains at zero.

Also I don't know if it would be out of scope, but it would be nice to filter checks by availability (completely glitchless, and maybe extra filter options for OI, Ground Jumps, Equip Swap, etc., or not idk). Maybe just gray them out, or maybe use a different color like red? As someone who is new to rando, it's easy for me to accidentally click a check that was actually impossible :). Maybe something like track-oot.net?

---- DO NOT EDIT BELOW THIS LINE ----
Playthrough id: clonbbbal0000ig08fs4s40c5

**Comment by christianlegge** [comment]
Added support for key rings.

As for the logic stuff, that was definitely the plan at some point. I honestly thought it was already in there but it looks like I actually never started work on it lol. You caught me at a bad time though because I just finished [working on a Paper Mario rando tracker](https://github.com/Phantom5800/pmr-tracker/pull/90) and I'm about as sick as you can get of looking at logic requirement arrays. I'll add it to the short list of stuff to work on for sure.

Thanks for reporting!
